### PR TITLE
Fixed the bitmap on all devices. + QRCode v6

### PR DESCRIPTION
**Pull request by Niximkk**
Thanks to @bmorcelli bitmaps will work on all devices automatically.

### CODE REVIEW

**Comment by Niximkk** [comment]
DONT MERGE YET.

**Comment by Niximkk** [comment]
Ready for merge.

**Comment by n0xa** [comment]
The cardputer binary that was built from this PR still has a black screen for several seconds in place of the logo on the Stick C Plus:
https://github.com/n0xa/m5stick-nemo/actions/runs/7717779020/artifacts/1206993186

**Comment by Niximkk** [comment]
Works on my machine 🫣

**Comment by Niximkk** [comment]
I'll take a look at this soon

**Comment by Niximkk** [comment]
Nope, the firmware works fine.

https://cdn.discordapp.com/attachments/1201981952773849208/1207773603161051166/20240215_163838.mp4

**Comment by Niximkk** [comment]
@n0xa are you sure you got the right bin file?

**Pull request closed without merging**
