### PR TITLE
Samsung Spam (Easy Setup Spam) as requested in issue #154.

### PR DESCRIPTION
**Pull request by danny8972**
full credits to Spooks4576
in this repository https://github.com/Spooks4576/Ghost_ESP/blob/main/src/components/ble_module/ble_module.h

Very much in progress builds fine on Arduino but I don't have any Samsung devices to test. Would love some help with that.
Feedback is very welcome.

### CODE REVIEW

**Comment by StingerFingersinmyass** [comment]
Thank you for realizing my idea, I understand my issue can be closed. 
https://github.com/n0xa/m5stick-nemo/issues/154

**Comment by StingerFingersinmyass** [comment]
It works, only there is a snag when the notification appears: When the REAL device appears, "Device" appears at the top, but "ESP32" appears at the end: 
изображение_2024-05-03_205924708
. Maybe there is some way to make the sending a bit faster. Basically everything works.

**Comment by danny8972** [comment]
Im a little confused by "REAL device" do you mean the ESP32 or you re-connecting with a legitimate Samsung watch and having continued problems.

**Comment by StingerFingersinmyass** [comment]
> Im a little confused by "REAL device" do you mean the ESP32 or you re-connecting with a legitimate Samsung watch and having continued problems.
Btw, everything was working perfectly fine until some point, but then the messages stopped showing at all.
Back to your question - yes, official devices have their own names depending on its type (Buds - " ", Watches - "Device").

**Comment by StingerFingersinmyass** [comment]
Maybe the problem lies in the code, because in fw Marauder for M5StickcPlus2 with M5Burner works perfectly honestly, you can try to compare your code and fw code here: 
https://github.com/ATOMNFT/M5stick-Marauder/blob/main/M5stickC%20Plus%201%20%26%202%20WiFi%20Marauder%200.13.10/WiFiScan.cpp
https://github.com/ATOMNFT/M5stick-Marauder/blob/main/M5stickC%20Plus%201%20%26%202%20WiFi%20Marauder%200.13.10/WiFiScan.h

**Comment by danny8972** [comment]
I think the reason the messages stop appearing lies in preventative measures taken by the Manufacturers to stop this attack. With marauder they have random MAC addresses which help bypass their measures. Random MAC has been added and will come out in the next release.

**Comment by danny8972** [comment]
Just did a quick check over the code, I really can't understand why the ESP32 is advertising it's self especially since we initialize it to a blank string in this code


  // Create the BLE Server
  BLEDevice::init("");
  BLEServer *pServer = BLEDevice::createServer();
  pAdvertising = pServer->getAdvertising();
  BLEAdvertisementData oAdvertisementData = BLEAdvertisementData();
  
  @n0xa 
Any Ideas for this weird behavior.

**Comment by mxrxtr** [comment]
Doesnt work

**Comment by danny8972** [comment]
Can you give me some error output or any other context?

**Comment by mxrxtr** [comment]
The Samsung spam doesnt advertise anything tried to reflash the software twice didnt do anything

**Comment by danny8972** [comment]
Maybe its a problem with the files you downloaded I have multiple branches in my pull request, Also do you have a Samsung device to view the advertisements, because it may not work on other devices.

**Comment by mxrxtr** [comment]
Yes i have a samsung device to test

**Comment by mxrxtr** [comment]
Could you give me the right bin then

**Pull request merged**
