### PR TITLE
Fixed the bitmap screen size for the M5StickCPlus

### PR DESCRIPTION
**Pull request by Niximkk**

### CODE REVIEW

**Comment by n0xa** [comment]
It's something, but still garbled on my StickC+

**Comment by Niximkk** [comment]
> It's something, but still garbled on my StickC+

Really? Mine works fine... Did you try the bitmap i sent?
(this one: https://e-z.tools/p/bdwmuv9943)

**Comment by n0xa** [comment]
Can you please add that to your PR? It looks like your two different PRs have some cross-contamination, too.

**Comment by Niximkk** [comment]
I will remake the pr, dont worry.

**Pull request closed without merging**
