### PR TITLE
Targetted Deauth Functionality and SD support to M5StickC devices

### PR DESCRIPTION
**Pull request by bmorcelli**
Added support do SD Card reader for M5StickC devices;

Added Deauthentication Attack, running from two places: 
 - 1: From Nemo Portal when cloned an AP from Wifi Scanning option
 - 2: From "Targ. Deauth" menu in Wifi menu.
The seccond option uses the wifi scanner function, to not rewrite menus and loop functions

The scanner details was showing wrong BSSID of the APs... I corrected that too.

The seccond option uses the wifi scanner function, to not rewrite menus and loop functions

Added support to Portuguese language.

Congratulations for your Job!

### CODE REVIEW

**Review by n0xa — COMMENTED** [review]
I cannot get this branch to compile cleanly for Stick C Plus. multiple defs of `ieee80211_raw_frame_sanity_check` and some of the BITMAP stuff that is fixed in my project seem to be missing. When I uncomment out the definition of raw_Fram_santy_check it crashes on trying to deauth. I'll try to look at this more when I have time. It seems to be close, but it is adding a lot of complexity and I need more time to review. It must build clean on all four supported platforms, though.

**Comment by bmorcelli** [comment]
Fixed the BITMAP, to sync with yours.

I also made a README with instructions to make DEAUTH compile without errors.

https://github.com/bmorcelli/m5stickC_Plus2-nemo/tree/main/DEAUTH%20Prerequisites

There is a .bat file that makes all the changes.

**Comment by n0xa** [comment]
I know the multiple definitions stuff probably crept in from how ESP32Marauder does a lot of stuff. Can you verify that there's no clean way to do what's needed in code to avoid those steps? One piece of feedback I've gotten is that NEMO is pretty easy to compile, and manually tweaking the compiler options buried in the platform configs is going to make it harder. I'm not 100% averse to it, but I'd like to make sure there's no other way.

**Comment by bmorcelli** [comment]
Unfortunately I didn't find a way to send the deauthentication frames without having to change the compiler's platform.txt.

I will continue researching a way to bypass sanity_check, which would probably lead to very advanced obfuscation techniques, and even so there is no guarantee that it will work.

With that in mind, I left the functionality optional, through #define DEAUTHER, so you can let it commented and let it to more advanced users.

**Comment by n0xa** [comment]
Let's re-convene on this after @vs4vijay helps me get the GitHub actions compiling images on the fly. Everyone wants Deauth, and you're on the right track. Targeted deauth is a good balance of useful vs chaos.

**Comment by bmorcelli** [comment]
Hello again...

I will update my code to match with the last version of Nemo... since the differences are not automattically done ... so i will close this pull request and open a new one, with clean changes..

**Pull request closed without merging**
