### PR TITLE
Creating new option on TV B GONE: Custom Code

### PR DESCRIPTION
**Pull request by IsaacLouzeiro**

### CODE REVIEW

**Comment by IsaacLouzeiro** [comment]
A new option has been added to the TV B GONE feature, allowing for custom IR codes. It is now possible to add new infrared codes contributed by new collaborators or reuse codes from other projects.
To add new codes, place the corresponding files in the 'codes' folder and link them to the project. Then, navigate to 'Custom_Ir_Codes.h' for inclusion. After that, go to the 'WORLD_IR_CODES.h' file, and at line 8838, you'll find an array 'const IrCode* const CustomCodes[]'. Inside this array, include the newly created file (based on the provided examples)."
I used the repository at [<link>](https://github.com/DjordjeMandic/Universal-IR-Blaster-TV-B-Gone) as a reference.

**Comment by IsaacLouzeiro** [comment]
Acabei de fazer um teste, anteriormente não funcionava em TV da marca LG, ao rodar o codigo customizado (Há codigos de TV LG), foi possível ligar e desligar normalmente.

**Comment by n0xa** [comment]
I dig it. Do you have a good way for average folks to capture new IR codes in a way that's compatible with this new framework? Examples might be a Circuit Playground Express or Flipper Zero that have IR receivers built in, or an IR reciver plugged into the M5Stick. That doesn't need to actually be baked into NEMO yet but One thing I'd love is for it to be easier to capture and add new codes. I'll test this out this weekend if I get time. I'm still in the process of packing and moving.

**Comment by IsaacLouzeiro** [comment]
This is my second step, using a receiver to capture and send the code to the "Custom" section. I'm diving into this implementation, but for now, all I've got is the good old manual add-on.

**Pull request merged**
